package Pages;

public enum LeftMenu {
    SKLEP_RTV, LCD, LED, TV3D, DVD, RTV,
    SKLEP_AGD,
    ZABAWKI,
    MILITARIA, WIATROWKI, WIATROWKI_KARABINKI, WIATROWKI_PISTOLETY,
    AKCESORIA, CELOWNIKI, SRUT, C02, TARCZE,
    AIRSOFTGUN, PAINTBALL,
    FOTOGRAFIA, APARATY, APARATY_KOMPAKTOWE, LUSTRZANKI,
    OBIEKTYWY, KARTY_PAMIECI, LAMPY_BLYSKOWE,
    ALBUMY, ENCYKLOPEDIE, DLA_DZIECI, BIOGRAFIE, INFORMATYKA, ZESTAWY, DLA_PELNOLETNICH,
    ZAAWANSOWANE_FILTRY, CHECKBOX, SLOWNIKI, WARTOSC, ZAKRES,
    WG_WYMIAROW, Z_WARIANTAMI, NIESTANDARDOWE,
    EBOOKI_AUDIOBOOKI, EBOOKI, AUDIOBOOKI,
    ZAMOW_SKLEP_INTERNETOWY
}
